python main_train.py \
--image_dir data/CT_RATE/ \
--ann_path data/CT_RATE/annotation.json \
--dataset_name CT_RATE \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--seed 9223
